services:
  fhem:
    image: ghcr.io/fhem/fhem-docker:5-bookworm
    container_name: fhem
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - "/home/${USER:-trasba}/.trasba/docker/fhem/data/:/opt/fhem/"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      FHEM_UID: 1000
      FHEM_GID: 1000
      TIMEOUT: 10
      RESTART: 1
    networks:
      - default

networks:
  default:
    enable_ipv6: true