version: '3.8'

services:
  samba:
    image: dperson/samba
    container_name: samba
    deploy:
      resources:
        limits:
          memory: 128m
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
    environment:
      TZ: ${TZ}
      USERID: ${UID}
      GROUPID: ${GID}
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./priv:/priv
      - ./pub:/pub
    command: '-s "pub;/pub;yes;no;yes" -s "priv;/priv;yes;no;no;${SMB_USER}" -u "${SMB_USER};${SMB_PASSWD};991;;991" -p'