services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      ACCOUNT_user1: ${password}
      #      UID_username: 1000
      #      GROUPS_auser1: family
      #      SAMBA_VOLUME_CONFIG_scan: "[scan]; path=/shares/scan; available =; valid users = user1; guest ok = yes; read on>
      SAMBA_VOLUME_CONFIG_share: |
        [share]
         path = /shares/share
         guest ok = yes
         browseable = yes
         read only = no
    volumes:
      - $HOME/.trasba/docker/samba/share:/shares/share
    ports:
      - 445:445
