---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#      - PASSWORD=password #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
#      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/${USER}/.trasba/docker/ddns-updater/config:/config
      - /home/${USER}/.trasba:/config/workspace
#    ports:
#     - 8443:8443
    restart: unless-stopped
    networks:
     - caddy

networks:
    caddy:
      name: ${CADDY_NET}
      external: true