# This docker-compose.yml file defines a simple service that runs the nginxdemos/hello image.
# It maps port 80 on the host to port 80 in the container, and ensures the container restarts unless explicitly stopped.
#

services:
  hello:
    container_name: hello
    image: nginxdemos/hello:latest
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
