services:
  web:
    image: eclipse-mosquitto:2 ###240530
    container_name: mqtt
    ports:
      - ${TCP_01}:${TCP_01}
    #          - ${TCP_02}
    volumes:
      - $HOME/.trasba/docker/mqtt/data:/mosquitto/data
      - $HOME/.trasba/docker/mqtt/config:/mosquitto/config
      - $HOME/.trasba/docker/mqtt/log:/mosquitto/log
    restart: always
    environment:
      - TZ=${TZ}
