---
services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    volumes:
      - "/home/${USER:-trasba}/.trasba/docker/jupyter/home:/home/jovyan
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # ports:
      # - 8888:8888
    networks:
      - caddy

networks:
  caddy:
    name: "${CADDY_NET:-caddy}"
    external: true