version: "3.9"

services:
  jupyter:
    image: jupyter/base-notebook:latest # 231108
    container_name: jupyter
    volumes:
      - ~/.trasba/docker/jupyter:/home/jovyan
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    # traefik network
    networks:
      - net
    labels:
      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.jupyter.entrypoints=https"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"

networks:
  # the network has to match the traefik network
  net:
    name: ${NET}
    external: true
