# run with docker-compose -f init.yml
# init django docker container, this will:
# * copy the /app folder to the local files system
# * finally you can run the docker-compose command
version: '3.7'

services:
  app:
    image: trasba/django:3.1.7 # as of 210326
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/tmp1
    command: sh -c "cp /app/* /tmp1 -r"
    environment:
      - DEBUG=1